# Generated by Django 4.2 on 2023-05-22 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("items", "0001_initial"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workorder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ls_workorder_id",
                    models.IntegerField(db_index=True, null=True, unique=True),
                ),
                ("time_in", models.DateTimeField(null=True)),
                ("eta_out", models.DateTimeField(null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("warranty", models.BooleanField(null=True)),
                ("tax", models.BooleanField(null=True)),
                ("archived", models.BooleanField(null=True)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("update_from_ls_time", models.DateTimeField(null=True)),
                ("item_description", models.CharField(max_length=100, null=True)),
                ("status", models.CharField(max_length=50, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workorders",
                        to="customers.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkorderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ls_workorder_line_id",
                    models.IntegerField(db_index=True, null=True, unique=True),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("update_from_ls_time", models.DateTimeField(db_index=True, null=True)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("unit_quantity", models.IntegerField(null=True)),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("tax", models.BooleanField(null=True)),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workorder_lines",
                        to="items.item",
                    ),
                ),
                (
                    "workorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workorder_lines",
                        to="workorders.workorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkorderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ls_workorder_item_id",
                    models.IntegerField(db_index=True, null=True, unique=True),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("unit_quantity", models.IntegerField(null=True)),
                ("tax", models.BooleanField(null=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("update_from_ls_time", models.DateTimeField(db_index=True, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workorder_items",
                        to="items.item",
                    ),
                ),
                (
                    "workorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workorder_items",
                        to="workorders.workorder",
                    ),
                ),
            ],
        ),
    ]
