# Generated by Django 4.2 on 2023-04-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workorders", "0002_alter_workorder_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorderitem",
            name="ls_workorder_item_id",
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="workorderitem",
            name="update_from_ls_time",
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="workorderline",
            name="ls_workorder_line_id",
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="workorderline",
            name="update_from_ls_time",
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
