# Generated by Django 4.2 on 2023-04-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workorders", "0003_alter_workorderitem_ls_workorder_item_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorder",
            name="ls_workorder_id",
            field=models.IntegerField(db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="workorderitem",
            name="ls_workorder_item_id",
            field=models.IntegerField(db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="workorderline",
            name="ls_workorder_line_id",
            field=models.IntegerField(db_index=True, null=True, unique=True),
        ),
    ]
