# Generated by Django 4.2 on 2023-04-25 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0003_alter_item_ls_item_id"),
        ("workorders", "0009_workorderline_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorderline",
            name="item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workorder_lines",
                to="items.item",
            ),
        ),
    ]
