# Generated by Django 4.2 on 2023-04-30 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("items", "0001_initial"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ls_sale_id",
                    models.IntegerField(db_index=True, null=True, unique=True),
                ),
                ("completed_time", models.DateTimeField(null=True)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("update_from_ls_time", models.DateTimeField(db_index=True, null=True)),
                ("completed", models.BooleanField(null=True)),
                ("archived", models.BooleanField(null=True)),
                ("voided", models.BooleanField(null=True)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="customers.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaleLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ls_sale_line_id",
                    models.IntegerField(db_index=True, null=True, unique=True),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("update_from_ls_time", models.DateTimeField(db_index=True, null=True)),
                ("unit_quantity", models.IntegerField(null=True)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "average_cost",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("tax", models.BooleanField(null=True)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("is_work_order", models.BooleanField(null=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_lines",
                        to="items.item",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_lines",
                        to="sales.sale",
                    ),
                ),
            ],
        ),
    ]
