# Generated by Django 4.2 on 2023-04-16 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ItemAttributes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attribute1", models.CharField(blank=True, max_length=255)),
                ("attribute2", models.CharField(blank=True, max_length=255)),
                ("attribute3", models.CharField(blank=True, max_length=255)),
                ("item_attribute_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ls_item_id", models.IntegerField(null=True)),
                (
                    "default_cost",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "average_cost",
                    models.DecimalField(decimal_places=4, max_digits=12, null=True),
                ),
                ("tax", models.BooleanField()),
                ("archived", models.BooleanField()),
                ("item_type", models.CharField(max_length=20)),
                ("serialized", models.BooleanField()),
                ("description", models.CharField(max_length=255)),
                ("model_year", models.IntegerField(null=True)),
                ("upc", models.CharField(blank=True, max_length=12)),
                ("custom_sku", models.CharField(blank=True, max_length=20)),
                ("manufacturer_sku", models.CharField(max_length=20)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("update_from_ls_time", models.DateTimeField(null=True)),
                ("item_matrix_id", models.IntegerField()),
                (
                    "item_attributes",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.itemattributes",
                    ),
                ),
            ],
        ),
    ]
