# Generated by Django 4.2 on 2023-04-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="sizes",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
