# Generated by Django 4.2 on 2023-04-25 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0004_alter_customer_ls_customer_id"),
        ("items", "0003_alter_item_ls_item_id"),
        ("serials", "0004_alter_serial_ls_serial_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serial",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="serials",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="serial",
            name="item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="serials",
                to="items.item",
            ),
        ),
    ]
