# Generated by Django 4.2 on 2023-05-11 17:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceFunctionalAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=5, unique=True)),
                ("name", models.CharField(max_length=30)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "code"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DeviceGPU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=5, unique=True)),
                ("name", models.CharField(max_length=30)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "GPU",
                "verbose_name_plural": "GPUs",
            },
        ),
        migrations.CreateModel(
            name="DevicePart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=5, unique=True)),
                ("name", models.CharField(max_length=30)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "code"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DeviceProcessorType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=5, unique=True)),
                ("name", models.CharField(max_length=30)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "code"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DeviceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=5, unique=True)),
                ("name", models.CharField(max_length=30)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "code"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "processor_speed",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                ("season", models.CharField(max_length=1, null=True)),
                (
                    "year",
                    models.IntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1976),
                            django.core.validators.MaxValueValidator(2023),
                        ],
                    ),
                ),
                (
                    "storage",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "ram",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, null=True, verbose_name="RAM"
                    ),
                ),
                ("description", models.TextField(null=True)),
                (
                    "device_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="items.devicetype",
                    ),
                ),
                (
                    "functional_attributes",
                    models.ManyToManyField(to="items.devicefunctionalattribute"),
                ),
                (
                    "gpu",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="items.devicegpu",
                        verbose_name="GPU",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="items.devicepart",
                    ),
                ),
                (
                    "processor_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="items.deviceprocessortype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DevicePartField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visible_fields", models.JSONField(default=dict)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="items.devicetype",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="items.devicepart",
                    ),
                ),
            ],
            options={
                "unique_together": {("device", "part")},
            },
        ),
    ]
