# Generated by Django 4.2 on 2023-05-11 17:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0002_devicefunctionalattribute_devicegpu_devicepart_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="devicegpu",
            options={
                "verbose_name": "Device GPU",
                "verbose_name_plural": "Device GPUs",
            },
        ),
    ]
