# Generated by Django 4.2 on 2023-05-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0003_alter_devicegpu_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="serial_number",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
