# Generated by Django 4.2 on 2023-04-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Workorder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ls_workorder_id", models.IntegerField(null=True)),
                ("time_in", models.DateTimeField()),
                ("eta_out", models.DateTimeField(null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("warranty", models.BooleanField()),
                ("tax", models.DecimalField(decimal_places=2, max_digits=10)),
                ("archived", models.BooleanField()),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("ls_customer_id", models.IntegerField()),
                ("ls_serialized_id", models.IntegerField()),
                ("ls_sale_id", models.IntegerField()),
                ("ls_sale_line_id", models.IntegerField()),
                ("ls_item_description", models.CharField(max_length=100)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
