# Generated by Django 4.2 on 2023-04-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workorders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="update_from_ls_time",
            field=models.DateTimeField(null=True),
        ),
    ]
