# Generated by Django 4.2 on 2023-04-11 16:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workorders", "0003_workorder_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workorder",
            name="ls_customer_id",
        ),
        migrations.RemoveField(
            model_name="workorder",
            name="ls_item_description",
        ),
        migrations.RemoveField(
            model_name="workorder",
            name="ls_sale_id",
        ),
        migrations.RemoveField(
            model_name="workorder",
            name="ls_sale_line_id",
        ),
        migrations.RemoveField(
            model_name="workorder",
            name="ls_serialized_id",
        ),
    ]
