# Generated by Django 4.2 on 2023-04-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workorders", "0004_remove_workorder_ls_customer_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorder",
            name="tax",
            field=models.BooleanField(),
        ),
    ]
