# Generated by Django 4.2 on 2023-04-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workorders", "0005_alter_workorder_tax"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorder",
            name="time_in",
            field=models.DateTimeField(null=True),
        ),
    ]
