# Generated by Django 4.2 on 2023-04-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="title",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
