# Generated by Django 4.2 on 2023-04-18 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("serials", "0001_initial"),
        ("workorders", "0001_initial"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="serials",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customers",
                to="serials.serial",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="workorders",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customers",
                to="workorders.workorder",
            ),
        ),
    ]
