# Generated by Django 4.2 on 2023-04-18 03:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0003_alter_customer_serials_alter_customer_workorders"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="serials",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="workorders",
        ),
    ]
