# Generated by Django 4.2 on 2023-04-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0003_alter_customer_ls_customer_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="ls_customer_id",
            field=models.IntegerField(db_index=True, null=True, unique=True),
        ),
    ]
