# Generated by Django 4.2 on 2023-04-10 14:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="phone",
            unique_together={("number", "customer")},
        ),
    ]
