# Generated by Django 4.1.7 on 2023-04-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="emails",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="phones",
        ),
        migrations.AddField(
            model_name="customer",
            name="emails",
            field=models.ManyToManyField(blank=True, to="customer.email"),
        ),
        migrations.AddField(
            model_name="customer",
            name="phones",
            field=models.ManyToManyField(blank=True, to="customer.phone"),
        ),
    ]
