# Generated by Django 4.2 on 2023-04-10 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_alter_phone_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="phone",
            unique_together={("number", "customer", "use_type")},
        ),
    ]
