# Generated by Django 4.1.7 on 2023-04-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="avg_cost",
            new_name="average_cost",
        ),
        migrations.AlterField(
            model_name="item",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="update_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
