# Generated by Django 4.1.7 on 2023-04-03 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_rename_avg_cost_item_average_cost_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="average_cost",
            field=models.DecimalField(decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="default_cost",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_attributes",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.itemattributes",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="model_year",
            field=models.IntegerField(null=True),
        ),
    ]
