# Generated by Django 4.1.7 on 2023-04-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_alter_item_average_cost_alter_item_default_cost_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="custom_sku",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_type",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="item",
            name="manufacturer_sku",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="item",
            name="upc",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name="item",
            name="updated_from_ls_time",
            field=models.DateTimeField(null=True),
        ),
    ]
