# Generated by Django 4.2 on 2023-04-14 12:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workorders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workorder",
            name="total",
        ),
    ]
