# Generated by Django 4.2 on 2023-04-18 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0003_alter_customer_serials_alter_customer_workorders"),
        ("workorders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorder",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workorders_related",
                to="customers.customer",
            ),
        ),
    ]
