# Generated by Django 4.2 on 2023-04-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workorders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="item_description",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
