# Generated by Django 4.2 on 2023-04-18 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0003_remove_item_serials"),
        ("workorders", "0002_alter_workorder_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkorderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ls_workorder_item_id", models.IntegerField(null=True)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("unit_quantity", models.IntegerField(null=True)),
                ("tax", models.BooleanField(null=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("update_from_ls_time", models.DateTimeField(null=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workorder_items",
                        to="items.item",
                    ),
                ),
                (
                    "workorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workorder_items",
                        to="workorders.workorder",
                    ),
                ),
            ],
        ),
    ]
