# Generated by Django 4.2 on 2023-04-18 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("workorders", "0003_workorderitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkorderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ls_workorder_line_id", models.IntegerField(null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("update_from_ls_time", models.DateTimeField(null=True)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("unit_quantity", models.IntegerField(null=True)),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("tax", models.BooleanField(null=True)),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "workorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workorder_lines",
                        to="workorders.workorder",
                    ),
                ),
            ],
        ),
    ]
