# Generated by Django 4.2 on 2023-04-25 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0003_alter_item_ls_item_id"),
        ("workorders", "0008_alter_workorder_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorderline",
            name="item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workorder_lines",
                to="items.item",
            ),
            preserve_default=False,
        ),
    ]
