# Generated by Django 4.2.1 on 2023-05-23 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("checklists", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testinstance",
            name="device",
        ),
        migrations.AddField(
            model_name="testinstance",
            name="device_part",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="checklists.devicepart",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="testinstance",
            name="device_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="checklists.devicetype",
            ),
            preserve_default=False,
        ),
    ]
