# Generated by Django 4.2 on 2023-04-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("serials", "0003_alter_serial_ls_serial_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serial",
            name="ls_serial_id",
            field=models.IntegerField(db_index=True, null=True, unique=True),
        ),
    ]
