# Generated by Django 4.2 on 2023-04-25 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0003_alter_item_ls_item_id"),
        ("serials", "0006_alter_serial_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serial",
            name="item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="serials_related",
                to="items.item",
            ),
        ),
    ]
