# Generated by Django 4.2 on 2023-04-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="ls_item_id",
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="update_from_ls_time",
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
