# Generated by Django 4.2 on 2023-04-18 03:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0002_item_serials"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="serials",
        ),
    ]
