# Generated by Django 4.2 on 2023-04-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0002_alter_item_ls_item_id_alter_item_update_from_ls_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="ls_item_id",
            field=models.IntegerField(db_index=True, null=True, unique=True),
        ),
    ]
