# Generated by Django 4.2 on 2023-05-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebay", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="failed",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="functionalattribute",
            name="failed",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="gpu",
            name="failed",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="part",
            name="failed",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="processortype",
            name="failed",
            field=models.BooleanField(null=True),
        ),
    ]
