# Generated by Django 4.2 on 2023-05-11 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ebay", "0002_device_failed_functionalattribute_failed_gpu_failed_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="failed",
        ),
        migrations.RemoveField(
            model_name="functionalattribute",
            name="failed",
        ),
        migrations.RemoveField(
            model_name="gpu",
            name="failed",
        ),
        migrations.RemoveField(
            model_name="part",
            name="failed",
        ),
        migrations.RemoveField(
            model_name="processortype",
            name="failed",
        ),
    ]
